# Generated by Django 3.0.4 on 2020-05-12 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('status', models.CharField(blank=True, choices=[('dlf', 'Не ищу работу'), ('ld', 'Рассматриваю предложения'), ('lf', 'Ищу работу')], default='dlf', max_length=3, verbose_name='Готовность к работе')),
                ('salary', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ожидаемое вознаграждение')),
                ('grade', models.CharField(blank=True, choices=[('B', 'Стажер'), ('J', 'Джуниор'), ('M', 'Миддл'), ('S', 'Синьор'), ('L', 'Лид')], default='J', max_length=1, verbose_name='Квалификация')),
                ('education', models.TextField(blank=True, null=True, verbose_name='Образование')),
                ('experience', models.TextField(blank=True, null=True, verbose_name='Опыт работы')),
                ('portfolio', models.URLField(blank=True, verbose_name='Ссылка на портфолио')),
                ('spec', models.ForeignKey(blank=True, default='2', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='vacancy.Speciality', verbose_name='Специализация')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_username', models.CharField(blank=True, max_length=20)),
                ('written_phone', models.CharField(blank=True, max_length=16)),
                ('written_cover_letter', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='vacancy.Vacancy')),
            ],
        ),
    ]
