# Generated by Django 3.0.4 on 2020-04-22 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('vacancy', '0002_auto_20200422_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('dlf', 'Не ищу работу'), ('ld', 'Рассматриваю предложения'), ('lf', 'Ищу работу')], default='dlf', max_length=3)),
                ('salary', models.PositiveIntegerField(blank=True)),
                ('grade', models.CharField(choices=[('B', 'Стажер'), ('J', 'Джуниор'), ('M', 'Миддл'), ('S', 'Синьор'), ('L', 'Лид')], default='J', max_length=1)),
                ('education', models.TextField(blank=True, verbose_name='Образование')),
                ('experience', models.TextField(blank=True, verbose_name='Специализация')),
                ('portfolio', models.TextField(blank=True)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_speciality', to='vacancy.Speciality')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_user', to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_username', models.CharField(max_length=20)),
                ('written_phone', models.CharField(max_length=16)),
                ('written_cover_letter', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.Profile')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='vacancy.Vacancy')),
            ],
        ),
    ]
