# Generated by Django 3.0.4 on 2020-04-28 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_auto_20200422_1502'),
        ('user_company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='portfolio',
            field=models.URLField(blank=True, verbose_name='Портфолио'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='salary',
            field=models.PositiveIntegerField(blank=True, verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_speciality', to='vacancy.Speciality', verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('dlf', 'Не ищу работу'), ('ld', 'Рассматриваю предложения'), ('lf', 'Ищу работу')], default='dlf', max_length=3, verbose_name='Статус'),
        ),
    ]
